server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer?driver=org.postgresql.Driver
    password: 'hggi'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true