server:
  port: 9090

spring:
  application:
    name: notification
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/notification?driver=org.postgresql.Driver
    password: 'hggi'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true